rules:
- id: detected-gitlab-token
  patterns:
  - pattern-regex: |-
      ("|'|`)?(glpat-[A-Za-z0-9_\-]{20,})("|'|`)?
  - pattern-not-regex: (?i)example|sample|test|fake|xxxxxx
  languages: [regex]
  message: GitLab Token detected
  severity: ERROR
  metadata:
    cwe:
    - 'CWE-798: Use of Hard-coded Credentials'
    category: security
    technology:
    - secrets
    - gitlab
    confidence: HIGH
    owasp:
    - A07:2021 - Identification and Authentication Failures
    references:
    - https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures
    cwe2022-top25: true
    cwe2021-top25: true
    subcategory:
    - audit
    likelihood: HIGH
    impact: HIGH
    vulnerability_class:
    - Hard-coded Secrets